version: '3'
services:
  app:
    build: .
    volumes:
      - .dockervenv:/src/.venv
      - .:/src
    ports:
      - 8000:8000
  postgis:
    image: mdillon/postgis
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=password"
    volumes_from:
      - data
    ports:
      - "25432:5432"
  data:
    image: "busybox"
    volumes:
      - "db:/var/lib/postgresql/data"

volumes:
  db:
    driver: local
